# Generated by Django 5.0 on 2023-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='unit',
            field=models.CharField(blank=True, default='%', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='unit',
            field=models.CharField(blank=True, default='°C', max_length=30, null=True),
        ),
    ]
